### ISSUE TITLE
Solvable unsolvable nonagram

### ISSUE THREAD

**Issue by icecream17** [davidsover/davidsover.github.io#1]
Really cool website, first of all

I found a nonagram that can't be solved by the current version of the solver
```
{rows:[[1,1],[2,1],[1,1],[2,1],[2,1]],columns:[[2,1],[1,2],[1,2],[1],[1,2]]}
```

![image](https://github.com/soverthe/soverthe.github.io/assets/58114641/c0f64cfc-f5d0-412f-abad-22f7ad67ae1a)

However, I don't know any good strategy other than brute force for this. Here, if you guess green, you get contradictions, 
![image](https://github.com/soverthe/soverthe.github.io/assets/58114641/493fd8a4-48d4-4f9b-b32a-90f2b23dea5b)
so then it's not green, and it solves.
![image](https://github.com/soverthe/soverthe.github.io/assets/58114641/bb7e16d2-f51b-4bb7-a552-e5acc1b465f9)

(I know you said you were done with the project so I'll close this immediately, but I think it's interesting and wanted to share. Also it means there might be an even harder 6x6 nonagram. I might try to find it, but no promises)

Simpler repro: 
![image](https://github.com/soverthe/soverthe.github.io/assets/58114641/5582590b-96e6-452b-a6fd-5651d9502da6)

**Comment by soverthe** [comment]
Okay since you closed it right away it took me almost a year to see this but hey xd
Yeah my solver only looks at individual lines so it can't solve these kinds of stuff, there's no doubt that smarter solvers could exist
